In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/processed/cleaned_data.csv")

C:\Users\Faisal\AppData\Local\Temp\ipykernel_8220\45199494.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/cleaned_data.csv")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,revenue,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,20.34

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524878 entries, 0 to 524877
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    524878 non-null  object
 1   StockCode    524878 non-null  object
 2   Description  524878 non-null  object
 3   Quantity     524878 non-null  int64
 4   InvoiceDate  524878 non-null  object
 5   UnitPrice    524878 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      524878 non-null  object
 8   revenue      524878 non-null  float64
 9   Revenue      524878 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 40.0+ MB

In [10]:
df['CustomerID']=df['CustomerID'].astype("Int64")

In [12]:
df['CustomerID'].dtype

Int64Dtype()

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524878 entries, 0 to 524877
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    524878 non-null  object
 1   StockCode    524878 non-null  object
 2   Description  524878 non-null  object
 3   Quantity     524878 non-null  int64
 4   InvoiceDate  524878 non-null  object
 5   UnitPrice    524878 non-null  float64
 6   CustomerID   392692 non-null  Int64
 7   Country      524878 non-null  object
 8   revenue      524878 non-null  float64
 9   Revenue      524878 non-null  float64
dtypes: Int64(1), float64(3), int64(1), object(5)
memory usage: 40.5+ MB

In [14]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [16]:
df['InvoiceDate'].dtype

dtype('<M8[ns]')

In [18]:
df['year'] = df['InvoiceDate'].dt.year
df['month'] = df['InvoiceDate'].dt.month

In [19]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,revenue,Revenue,year,month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,15.30,2010,12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,20.34,2010,12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,22.00,2010,12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,20.34,2010,12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,20.34,2010,12

In [23]:
df.drop("revenue",axis=1,inplace=True)

In [25]:
df['StockCode'].nunique()

3922

In [26]:
df['CustomerID'].nunique()

4338

In [27]:
df['Country'].nunique()

38

In [28]:
df['InvoiceNo'].nunique()

19962